'use client';

import React, { useState } from 'react';
import { FileText, Globe, Users, Calendar, BookOpen, Image, Download, Zap } from 'lucide-react';

export default function WizardPage() {
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState({
    keywords: [] as string[],
    keyPersons: [] as string[],
    dateRange: '',
    region: '',
    writingStyle: 'professional',
    depth: 'medium',
    language: 'english',
    includeVisuals: true
  });
  const [generatedContent, setGeneratedContent] = useState('');

  const updateFormData = (field: string, value: any) => {
    setFormData({ ...formData, [field]: value });
  };

  const nextStep = () => {
    if (step < 8) setStep(step + 1);
    if (step === 8 && !generatedContent) generateContent();
  };

  const prevStep = () => {
    if (step > 1) setStep(step - 1);
  };

  const generateContent = () => {
    const content = `# ${formData.keywords.join(', ')} - Transport Analysis

## Executive Summary
This comprehensive analysis covers recent developments in ${formData.keywords.join(', ')} within the Korean transportation sector.

## Introduction
The Korean transportation industry is experiencing rapid transformation, particularly in areas related to ${formData.keywords[0] || 'smart mobility'}.

## Key Developments
${formData.keywords.map((kw, i) => `
### ${i + 1}. ${kw}
Recent advancements in ${kw} have shown promising results. Key stakeholders including ${formData.keyPersons.join(', ') || 'industry experts'} have been instrumental in driving these changes.
`).join('')}

## Regional Analysis
Focus Region: ${formData.region || 'Seoul Metropolitan Area'}

The implementation of new transport technologies in ${formData.region || 'Seoul'} has set benchmarks for other cities to follow.

## Expert Insights
${formData.keyPersons.map(person => `- **${person}**: Leading voice in transport innovation`).join('\n') || '- Industry experts continue to provide valuable guidance'}

## Future Outlook
The next phase of development will focus on:
- Enhanced connectivity
- Sustainable solutions
- User-centric design
- Data-driven decision making

## Conclusion
The Korean transport sector continues to lead in innovation, with ${formData.keywords.join(', ')} at the forefront of this transformation.

---
*Generated by Hot Korea Transport News AI*
*Language: ${formData.language} | Style: ${formData.writingStyle} | Depth: ${formData.depth}*`;

    setGeneratedContent(content);
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white py-12">
      <div className="container mx-auto px-4">
        {/* Progress Bar */}
        <div className="max-w-4xl mx-auto mb-8">
          <div className="flex justify-between mb-2">
            {[1,2,3,4,5,6,7,8].map(s => (
              <div key={s} className={`w-10 h-10 rounded-full flex items-center justify-center font-bold ${s <= step ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-500'}`}>
                {s}
              </div>
            ))}
          </div>
          <div className="bg-gray-200 h-2 rounded-full">
            <div className="bg-blue-600 h-2 rounded-full transition-all" style={{width: `${(step/8)*100}%`}}></div>
          </div>
        </div>

        {/* Step Content */}
        <div className="max-w-4xl mx-auto bg-white rounded-xl shadow-lg p-8">
          {step === 1 && <KeywordStep data={formData} updateData={updateFormData} />}
          {step === 2 && <KeyPersonsStep data={formData} updateData={updateFormData} />}
          {step === 3 && <TemporalStep data={formData} updateData={updateFormData} />}
          {step === 4 && <StyleStep data={formData} updateData={updateFormData} />}
          {step === 5 && <DepthStep data={formData} updateData={updateFormData} />}
          {step === 6 && <VisualsStep data={formData} updateData={updateFormData} />}
          {step === 7 && <LanguageStep data={formData} updateData={updateFormData} />}
          {step === 8 && <ReviewStep data={formData} content={generatedContent} />}

          {/* Navigation */}
          <div className="flex justify-between mt-8 pt-8 border-t">
            <button 
              onClick={prevStep}
              disabled={step === 1}
              className="px-6 py-3 border-2 rounded-lg font-semibold disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50"
            >
              Back
            </button>
            <button 
              onClick={nextStep}
              className="px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700"
            >
              {step === 8 ? (generatedContent ? 'Regenerate' : 'Generate Content') : 'Next Step'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// Step Components
function KeywordStep({ data, updateData }: any) {
  const [inputValue, setInputValue] = useState('');
  
  const addKeyword = () => {
    if (inputValue.trim() && !data.keywords.includes(inputValue.trim())) {
      updateData('keywords', [...data.keywords, inputValue.trim()]);
      setInputValue('');
    }
  };

  const removeKeyword = (keyword: string) => {
    updateData('keywords', data.keywords.filter((k: string) => k !== keyword));
  };

  const suggestions = ['KTX', 'Seoul Metro', 'Autonomous Vehicle', 'Smart City', 'Hyperloop', 'Electric Bus', 'Mobility Platform'];

  return (
    <div>
      <h2 className="text-2xl font-bold mb-2">Step 1: Configure Keywords</h2>
      <p className="text-gray-600 mb-6">Add keywords to focus your transport content</p>
      
      <div className="mb-4">
        <label className="block text-sm font-medium mb-2">Add Keywords</label>
        <div className="flex gap-2">
          <input
            type="text"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyPress={(e) => e.key === 'Enter' && addKeyword()}
            placeholder="e.g., KTX, autonomous bus, Seoul Metro"
            className="flex-1 px-4 py-2 border-2 rounded-lg focus:border-blue-500 outline-none"
          />
          <button onClick={addKeyword} className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
            Add
          </button>
        </div>
      </div>

      <div className="flex flex-wrap gap-2 mb-6">
        {data.keywords.map((keyword: string) => (
          <span key={keyword} className="px-3 py-1 bg-blue-100 text-blue-800 rounded-full flex items-center gap-2">
            {keyword}
            <button onClick={() => removeKeyword(keyword)} className="text-blue-600 hover:text-blue-800 font-bold">×</button>
          </span>
        ))}
      </div>

      <div>
        <p className="text-sm font-medium mb-2">Suggested Keywords:</p>
        <div className="flex flex-wrap gap-2">
          {suggestions.map((suggestion) => (
            <button
              key={suggestion}
              onClick={() => !data.keywords.includes(suggestion) && updateData('keywords', [...data.keywords, suggestion])}
              className="px-3 py-1 text-sm border-2 rounded-full hover:bg-gray-100"
            >
              + {suggestion}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

function KeyPersonsStep({ data, updateData }: any) {
  const [inputValue, setInputValue] = useState('');
  
  const addPerson = () => {
    if (inputValue.trim() && !data.keyPersons.includes(inputValue.trim())) {
      updateData('keyPersons', [...data.keyPersons, inputValue.trim()]);
      setInputValue('');
    }
  };

  const removePerson = (person: string) => {
    updateData('keyPersons', data.keyPersons.filter((p: string) => p !== person));
  };

  return (
    <div>
      <h2 className="text-2xl font-bold mb-2">Step 2: Key Persons</h2>
      <p className="text-gray-600 mb-6">Add relevant officials, experts, or researchers to mention</p>
      
      <div className="mb-4">
        <label className="block text-sm font-medium mb-2">Add Key Person</label>
        <div className="flex gap-2">
          <input
            type="text"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyPress={(e) => e.key === 'Enter' && addPerson()}
            placeholder="e.g., Minister of Transport, Dr. Kim"
            className="flex-1 px-4 py-2 border-2 rounded-lg focus:border-blue-500 outline-none"
          />
          <button onClick={addPerson} className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
            Add
          </button>
        </div>
      </div>

      <div className="flex flex-wrap gap-2">
        {data.keyPersons.map((person: string) => (
          <span key={person} className="px-3 py-1 bg-green-100 text-green-800 rounded-full flex items-center gap-2">
            {person}
            <button onClick={() => removePerson(person)} className="text-green-600 hover:text-green-800 font-bold">×</button>
          </span>
        ))}
      </div>
    </div>
  );
}

function TemporalStep({ data, updateData }: any) {
  return (
    <div>
      <h2 className="text-2xl font-bold mb-2">Step 3: Temporal Context</h2>
      <p className="text-gray-600 mb-6">Specify time period and region for your analysis</p>
      
      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium mb-2">Time Period</label>
          <select 
            value={data.dateRange}
            onChange={(e) => updateData('dateRange', e.target.value)}
            className="w-full px-4 py-2 border-2 rounded-lg focus:border-blue-500 outline-none"
          >
            <option value="">Select period</option>
            <option value="last-week">Last Week</option>
            <option value="last-month">Last Month</option>
            <option value="last-quarter">Last Quarter</option>
            <option value="last-year">Last Year</option>
            <option value="2024">Year 2024</option>
          </select>
        </div>
        
        <div>
          <label className="block text-sm font-medium mb-2">Focus Region</label>
          <select 
            value={data.region}
            onChange={(e) => updateData('region', e.target.value)}
            className="w-full px-4 py-2 border-2 rounded-lg focus:border-blue-500 outline-none"
          >
            <option value="">Select region</option>
            <option value="Seoul">Seoul</option>
            <option value="Busan">Busan</option>
            <option value="Incheon">Incheon</option>
            <option value="Nationwide">Nationwide</option>
            <option value="Asia-Pacific">Asia-Pacific Region</option>
          </select>
        </div>
      </div>
    </div>
  );
}

function StyleStep({ data, updateData }: any) {
  const styles = [
    { value: 'casual', label: 'Casual', desc: 'Friendly and conversational' },
    { value: 'professional', label: 'Professional', desc: 'Business-appropriate tone' },
    { value: 'technical', label: 'Technical', desc: 'Industry jargon and detail' },
    { value: 'academic', label: 'Academic', desc: 'Scholarly and formal' }
  ];

  return (
    <div>
      <h2 className="text-2xl font-bold mb-2">Step 4: Writing Style</h2>
      <p className="text-gray-600 mb-6">Choose the tone that matches your audience</p>
      
      <div className="grid grid-cols-2 gap-4">
        {styles.map(style => (
          <button
            key={style.value}
            onClick={() => updateData('writingStyle', style.value)}
            className={`p-4 border-2 rounded-lg text-left transition ${
              data.writingStyle === style.value ? 'border-blue-600 bg-blue-50' : 'border-gray-200 hover:border-blue-300'
            }`}
          >
            <div className="font-semibold text-lg mb-1">{style.label}</div>
            <div className="text-sm text-gray-600">{style.desc}</div>
          </button>
        ))}
      </div>
    </div>
  );
}

function DepthStep({ data, updateData }: any) {
  const depths = [
    { value: 'short', label: 'Short', words: '300-500 words', desc: 'Quick updates and news' },
    { value: 'medium', label: 'Medium', words: '800-1200 words', desc: 'Standard blog posts' },
    { value: 'long', label: 'Long', words: '1500-2000 words', desc: 'In-depth analysis' },
    { value: 'comprehensive', label: 'Comprehensive', words: '2000+ words', desc: 'Deep research reports' }
  ];

  return (
    <div>
      <h2 className="text-2xl font-bold mb-2">Step 5: Content Depth</h2>
      <p className="text-gray-600 mb-6">Select the length and detail level</p>
      
      <div className="space-y-3">
        {depths.map(depth => (
          <button
            key={depth.value}
            onClick={() => updateData('depth', depth.value)}
            className={`w-full p-4 border-2 rounded-lg text-left transition ${
              data.depth === depth.value ? 'border-blue-600 bg-blue-50' : 'border-gray-200 hover:border-blue-300'
            }`}
          >
            <div className="flex justify-between items-center mb-1">
              <span className="font-semibold text-lg">{depth.label}</span>
              <span className="text-sm text-gray-500">{depth.words}</span>
            </div>
            <div className="text-sm text-gray-600">{depth.desc}</div>
          </button>
        ))}
      </div>
    </div>
  );
}

function VisualsStep({ data, updateData }: any) {
  return (
    <div>
      <h2 className="text-2xl font-bold mb-2">Step 6: Visual Assets</h2>
      <p className="text-gray-600 mb-6">Configure visual elements for your content</p>
      
      <div className="space-y-4">
        <label className="flex items-center p-4 border-2 rounded-lg cursor-pointer hover:bg-gray-50">
          <input
            type="checkbox"
            checked={data.includeVisuals}
            onChange={(e) => updateData('includeVisuals', e.target.checked)}
            className="w-5 h-5 mr-3"
          />
          <div>
            <div className="font-semibold">Include AI-Generated Images</div>
            <div className="text-sm text-gray-600">Add relevant transport imagery</div>
          </div>
        </label>
        
        <label className="flex items-center p-4 border-2 rounded-lg cursor-pointer hover:bg-gray-50">
          <input type="checkbox" className="w-5 h-5 mr-3" />
          <div>
            <div className="font-semibold">Generate Infographics</div>
            <div className="text-sm text-gray-600">Create data visualizations</div>
          </div>
        </label>
        
        <label className="flex items-center p-4 border-2 rounded-lg cursor-pointer hover:bg-gray-50">
          <input type="checkbox" className="w-5 h-5 mr-3" />
          <div>
            <div className="font-semibold">Include Data Tables</div>
            <div className="text-sm text-gray-600">Add structured data displays</div>
          </div>
        </label>
      </div>
    </div>
  );
}

function LanguageStep({ data, updateData }: any) {
  const languages = [
    { value: 'korean', label: '🇰🇷 Korean', native: '한국어' },
    { value: 'english', label: '🇺🇸 English', native: 'English' },
    { value: 'chinese', label: '🇨🇳 Chinese', native: '中文' },
    { value: 'japanese', label: '🇯🇵 Japanese', native: '日本語' },
    { value: 'spanish', label: '🇪🇸 Spanish', native: 'Español' },
    { value: 'arabic', label: '🇸🇦 Arabic', native: 'العربية' },
    { value: 'french', label: '🇫🇷 French', native: 'Français' },
    { value: 'german', label: '🇩🇪 German', native: 'Deutsch' }
  ];

  return (
    <div>
      <h2 className="text-2xl font-bold mb-2">Step 7: Output Language</h2>
      <p className="text-gray-600 mb-6">Select the language for your generated content</p>
      
      <div className="grid grid-cols-2 gap-3">
        {languages.map(lang => (
          <button
            key={lang.value}
            onClick={() => updateData('language', lang.value)}
            className={`p-4 border-2 rounded-lg text-left transition ${
              data.language === lang.value ? 'border-blue-600 bg-blue-50' : 'border-gray-200 hover:border-blue-300'
            }`}
          >
            <div className="font-semibold">{lang.label}</div>
            <div className="text-sm text-gray-600">{lang.native}</div>
          </button>
        ))}
      </div>
    </div>
  );
}

function ReviewStep({ data, content }: any) {
  const downloadMarkdown = () => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'transport-blog.md';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div>
      <h2 className="text-2xl font-bold mb-2">Step 8: Review & Generate</h2>
      <p className="text-gray-600 mb-6">Review your settings and generate content</p>
      
      {!content ? (
        <div className="bg-gray-50 rounded-lg p-6 space-y-3">
          <div><strong>Keywords:</strong> {data.keywords.join(', ') || 'None'}</div>
          <div><strong>Key Persons:</strong> {data.keyPersons.join(', ') || 'None'}</div>
          <div><strong>Period:</strong> {data.dateRange || 'Not specified'}</div>
          <div><strong>Region:</strong> {data.region || 'Not specified'}</div>
          <div><strong>Style:</strong> {data.writingStyle}</div>
          <div><strong>Depth:</strong> {data.depth}</div>
          <div><strong>Language:</strong> {data.language}</div>
          <div><strong>Visuals:</strong> {data.includeVisuals ? 'Yes' : 'No'}</div>
        </div>
      ) : (
        <div>
          <div className="bg-gray-50 rounded-lg p-6 mb-4 max-h-96 overflow-y-auto">
            <pre className="whitespace-pre-wrap text-sm">{content}</pre>
          </div>
          <div className="flex gap-3 flex-wrap">
            <button onClick={downloadMarkdown} className="px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 flex items-center gap-2">
              <Download size={20} />
              Download Markdown
            </button>
            <button className="px-6 py-3 bg-gray-600 text-white rounded-lg hover:bg-gray-700">
              Export as PDF
            </button>
            <button className="px-6 py-3 bg-gray-600 text-white rounded-lg hover:bg-gray-700">
              Export as Word
            </button>
          </div>
        </div>
      )}
    </div>
  );
}